// Runs only against a disposable workspace: creates projects/members and renews its owner token.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const os = require('node:os');
const base = process.env.TEAM_BROWSER_URL || 'http://127.0.0.1:17430';
const artifacts = process.env.BROWSER_ARTIFACT_DIR || fs.mkdtempSync(path.join(os.tmpdir(), 'werkbord-browser-'));
fs.mkdirSync(artifacts, { recursive: true });
const tokenFile = process.env.TEAM_BROWSER_TOKEN_FILE;
let token = process.env.TEAM_BROWSER_TOKEN || (tokenFile && fs.readFileSync(tokenFile, 'utf8').match(/wbt_[a-zA-Z0-9]+/)[0]);
if (!token)
    throw Error('Set TEAM_BROWSER_TOKEN or TEAM_BROWSER_TOKEN_FILE for a disposable sole-owner workspace.');
async function api(method, path, data, credential = token) {
    const res = await fetch(base + '/api/team/v1' + path, { method, headers: { Authorization: 'Bearer ' + credential, 'Content-Type': 'application/json' }, body: data ? JSON.stringify(data) : undefined });
    const text = await res.text();
    let body;
    try {
        body = JSON.parse(text);
    }
    catch { }
    ;
    if (res.status >= 400)
        throw Error(method + ' ' + path + ' ' + res.status + ' ' + text);
    return body;
}
(async () => {
    const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
    let errors = [];
    const ctx = await browser.newContext();
    const page = await ctx.newPage();
    page.on('pageerror', e => errors.push(e.message));
    page.setDefaultTimeout(10000);
    const p = await api('POST', '/projects', { name: 'Alpha ' + Date.now(), repository: 'https://github.com/acme/shop' });
    const q = await api('POST', '/projects', { name: 'Beta ' + Date.now(), repository: 'https://github.com/acme/shop-b' });
    let k = await api('POST', `/projects/${p.id}/tickets`, { title: 'Concurrent ticket', description: 'Original description', requirements: 'Original context', status: 'available' });
    k = await api('POST', `/projects/${p.id}/tickets/${k.id}/claim`);
    await page.goto(base + '/#token=' + token);
    const primary = page.getByRole('navigation', { name: 'Werkbord Team', exact: true });
    assert.equal(await page.getByRole('navigation', { name: 'Team administration' }).count(), 0, 'administration is only shown inside Settings');
    assert.equal(await page.locator('.note, .tiles').count(), 0, 'the explanation and summary boxes no longer compete with work');
    await page.getByRole('navigation', { name: 'Settings', exact: true }).getByRole('button', { name: 'Settings', exact: true }).click();
    assert.equal(await page.getByRole('navigation', { name: 'Team administration' }).getByRole('button', { name: 'Members', exact: true }).count(), 0, 'Members belongs in the main navigation');
    await primary.getByRole('button', { name: 'Members', exact: true }).click();
    await page.locator('.member-manage').first().locator('summary').click();
    await page.getByRole('button', { name: 'New token', exact: true }).first().click();
    await page.getByText('Your token', { exact: true }).waitFor();
    const fresh = await page.locator('.secret code').first().textContent();
    assert.notEqual(fresh, token);
    assert.equal(await page.evaluate(() => sessionStorage.getItem('werkbord-team-token')), fresh);
    assert.equal((await fetch(base + '/api/team/v1/me', { headers: { Authorization: 'Bearer ' + token } })).status, 401);
    token = fresh;
    fs.writeFileSync(path.join(artifacts, 'active-token.txt'), token, { mode: 0o600 });
    await page.reload();
    await page.getByRole('button', { name: 'Sign out', exact: true }).waitFor();
    console.log('PASS Settings disclosure, primary Members deep-link reload, self rotation and credential persistence');
    // Missing URL parameters reset older state, including on Back and Forward.
    await page.goto(base + '/');
    await page.locator('nav [aria-current="page"]').filter({ hasText: 'Workspace' }).waitFor();
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await page.getByRole('button', { name: q.name, exact: true }).click();
    await page.waitForFunction(id => document.querySelector('[name="project-switch"]')?.value === id, q.id);
    await page.goBack();
    await page.locator('nav [aria-current="page"]').filter({ hasText: 'Projects' }).waitFor();
    assert.deepEqual(await page.evaluate(() => [state.tab, state.projectId, state.ticketId]), ['projects', null, null]);
    await page.goBack();
    await page.locator('nav [aria-current="page"]').filter({ hasText: 'Workspace' }).waitFor();
    assert.deepEqual(await page.evaluate(() => [state.tab, state.projectId, state.ticketId]), ['workspace', null, null]);
    await page.goForward();
    await page.locator('nav [aria-current="page"]').filter({ hasText: 'Projects' }).waitFor();
    assert.deepEqual(await page.evaluate(() => [state.tab, state.projectId, state.ticketId]), ['projects', null, null]);
    await page.goForward();
    await page.waitForFunction(id => document.querySelector('[name="project-switch"]')?.value === id, q.id);
    await page.goto(base + `/?tab=invalid&project=&ticket=`);
    await page.locator('nav [aria-current="page"]').filter({ hasText: 'Workspace' }).waitFor();
    assert.deepEqual(await page.evaluate(() => [state.tab, state.projectId, state.ticketId]), ['workspace', null, null]);
    await page.goto(base + `/?tab=people&project=${p.id}`);
    await page.getByRole('heading', { name: /^People on this project/ }).waitFor();
    await page.reload();
    await page.getByRole('heading', { name: /^People on this project/ }).waitFor();
    console.log('PASS missing/empty URL state, fallback tab, browser Back/Forward, People deep-link reload');
    await page.goto(base + `/?tab=board&project=${p.id}&ticket=${k.id}`);
    await page.getByText('Edit this ticket', { exact: true }).click();
    const editTitle = page.locator(`[name="e-title-${k.id}"]`);
    await editTitle.fill('Draft title');
    await page.locator(`[name="e-desc-${k.id}"]`).fill('');
    const req = page.locator(`[name="e-reqs-${k.id}"]`);
    await req.fill('Draft requirements');
    await req.press('Tab');
    await req.focus();
    await req.evaluate(e => e.setSelectionRange(5, 5));
    const ctx2 = await browser.newContext();
    const other = await ctx2.newPage();
    await other.goto(base + '/#token=' + token);
    await other.getByRole('button', { name: 'Sign out', exact: true }).waitFor();
    const changed = await api('PATCH', `/projects/${p.id}/tickets/${k.id}`, { title: 'Other client title', description: 'Other client description', version: k.version });
    await page.getByText(/Someone changed this ticket/).waitFor();
    assert.equal(await editTitle.inputValue(), 'Draft title');
    assert.equal(await page.locator(`[name="e-desc-${k.id}"]`).inputValue(), '');
    assert.equal(await req.inputValue(), 'Draft requirements');
    assert.equal(await req.evaluate(e => document.activeElement === e && e.selectionStart === 5), true);
    assert.equal(await req.evaluate(e => e.closest('details').open), true);
    const response = page.waitForResponse(r => r.request().method() === 'PATCH' && r.url().includes(k.id));
    await page.locator(`[data-ticket-id="${k.id}"]`).getByRole('button', { name: 'Save', exact: true }).click();
    assert.equal((await response).status(), 409);
    const unchanged = await api('GET', `/projects/${p.id}/tickets/${k.id}`);
    assert.equal(unchanged.title, changed.title);
    await page.getByRole('button', { name: 'Load latest version', exact: true }).click();
    await page.waitForFunction(id => document.querySelector('[name="e-title-' + id + '"]')?.value === 'Other client title', k.id);
    console.log('PASS concurrent editors, stale-version rejection, intentional empty text, disclosure, keyboard focus, conflict recovery');
    // Independent drafts survive navigation without carrying into another project.
    await page.goto(base + `/?tab=board&project=${p.id}`);
    await page.getByRole('button', { name: 'New ticket', exact: true }).waitFor();
    await page.locator('body').press('n');
    await page.waitForFunction(() => document.activeElement?.name === 't-title');
    await page.locator('[name="t-title"]').fill('Alpha draft');
    await page.locator('[name="project-switch"]').selectOption(q.id);
    await page.locator('[name="t-title"]').waitFor();
    await page.waitForFunction(() => document.querySelector('[name="t-title"]')?.value === '');
    await page.locator('[name="t-title"]').fill('Beta draft');
    await page.locator('[name="project-switch"]').selectOption(p.id);
    await page.waitForFunction(() => document.querySelector('[name="t-title"]')?.value === 'Alpha draft');
    await page.getByRole('button', { name: 'Activity', exact: true }).click();
    await page.getByRole('button', { name: 'Board', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('[name="t-title"]')?.value === 'Alpha draft');
    console.log('PASS project-scoped drafts and round-trip navigation');
    // Actual reported commits are visible from Board details.
    await api('PUT', `/projects/${p.id}/tickets/${k.id}/git`, { commits: [{ sha: 'a'.repeat(40), subject: 'Verified browser commit', author: 'Ada', committedAt: new Date().toISOString() }], pullRequest: { number: 7, url: 'https://github.com/acme/shop/pull/7', state: 'open', draft: true, mergeable: 'conflicting', baseBranch: 'main', ahead: 8, behind: 3 } });
    await page.getByRole('button', { name: 'Other client title', exact: true }).click();
    await page.getByText('Verified browser commit', { exact: false }).waitFor();
    assert(page.url().includes('ticket=' + k.id));
    await page.goBack();
    await page.waitForFunction(() => !new URL(location.href).searchParams.has('ticket'));
    await page.goForward();
    await page.getByText('Verified browser commit', { exact: false }).waitFor();
    await page.getByText('Record branch and pull request', { exact: true }).click();
    await page.locator(`[name="g-state-${k.id}"]`).selectOption('closed');
    await api('POST', '/members', { name: 'Refresh trigger ' + Date.now() });
    await page.waitForTimeout(400);
    assert.equal(await page.locator(`[name="g-state-${k.id}"]`).inputValue(), 'closed');
    console.log('PASS Board commits, direct links, browser back/forward, select draft retention');
    // Reconnect leaves edits in place and refreshes authoritative server state.
    if (!await editTitle.isVisible())
        await page.getByText('Edit this ticket', { exact: true }).click();
    await ctx.setOffline(true);
    await page.locator(`[name="e-title-${k.id}"]`).fill('Reconnect draft');
    await ctx.setOffline(false);
    await api('POST', '/members', { name: 'Reconnect trigger ' + Date.now() });
    await page.waitForTimeout(1000);
    assert.equal(await editTitle.inputValue(), 'Reconnect draft');
    console.log('PASS reconnect draft recovery');
    await api('POST', `/projects/${p.id}/tickets/${k.id}/submit`, {});
    await page.getByRole('button', { name: 'Mark done', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Mark done', exact: true }).isDisabled(), true);
    await page.getByRole('button', { name: 'Reviews', exact: true }).click();
    await page.getByText(/pull request is still open/).first().waitFor();
    assert.equal(await page.getByRole('button', { name: 'Mark done', exact: true }).first().isDisabled(), true);
    console.log('PASS consistent open-PR completion restriction in Board and Reviews');
    await page.getByRole('button', { name: 'Board', exact: true }).click();
    await page.locator('[name="t-title"]').waitFor();
    await page.getByRole('button', { name: 'Other client title', exact: true }).click();
    // Drag, close and restore retain the ticket's reports and use the server's rules.
    await page.locator('.ticket').getByRole('button', { name: 'Close', exact: true }).focus();
    await page.keyboard.press('Escape');
    await page.locator('.ticket').waitFor({ state: 'detached' });
    await page.getByRole('button', { name: 'Cancel new ticket', exact: true }).click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    const boardBounds = await page.locator('.board').boundingBox();
    assert.ok(boardBounds.width > 1000 && boardBounds.y + boardBounds.height > 940, 'the board fills available desktop width and height');
    await primary.getByRole('button', { name: 'Git', exact: true }).click();
    await page.getByRole('heading', { name: 'Git', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Open project ' + q.name, exact: true }).click();
    await page.waitForFunction(id => state.tab === 'repository' && state.projectId === id && state.data?.id === id, q.id);
    await page.getByRole('button', { name: 'Open project ' + p.name, exact: true }).click();
    await page.waitForFunction(id => state.tab === 'repository' && state.projectId === id && state.data?.id === id, p.id);
    await primary.getByRole('button', { name: 'Board', exact: true }).click();
    console.log('PASS N / Escape shortcuts, viewport-sized board and project switching that keeps the Git section');
    let dragged = await api('POST', `/projects/${p.id}/tickets`, { title: 'Team drag fixture', description: 'Keep this context', status: 'backlog' });
    await page.getByRole('button', { name: new RegExp(dragged.title + '$') }).waitFor();
    const assignResponse = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/assign'));
    await page.getByRole('button', { name: new RegExp(dragged.title + '$') }).locator('..').dragTo(page.getByRole('region', { name: 'In Progress', exact: true }));
    assert.equal((await assignResponse).status(), 200);
    await page.getByRole('region', { name: 'In Progress', exact: true }).getByRole('button', { name: new RegExp(dragged.title + '$') }).waitFor();
    dragged = await api('GET', `/projects/${p.id}/tickets/${dragged.id}`);
    assert.equal(dragged.status, 'in_progress');
    await page.getByRole('button', { name: new RegExp(dragged.title + '$') }).click();
    await page.getByRole('button', { name: 'Close ticket', exact: true }).click();
    await page.getByRole('button', { name: 'Restore ticket', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('button', { name: /^Archive \(/ }).click();
    await page.getByRole('button', { name: new RegExp(dragged.title + '$') }).waitFor();
    await page.getByRole('button', { name: 'Restore', exact: true }).click();
    await page.getByRole('button', { name: 'Back to board', exact: true }).click();
    await api('POST', `/projects/${p.id}/tickets/${dragged.id}/submit`, {});
    await api('POST', `/projects/${p.id}/tickets/${dragged.id}/complete`, {});
    await page.getByRole('button', { name: 'Clear Done', exact: true }).click();
    await page.getByRole('button', { name: /^Archive \(/ }).click();
    await page.getByRole('button', { name: new RegExp(dragged.title + '$') }).click();
    await page.getByText('Keep this context', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Restore ticket', exact: true }).click();
    await page.getByRole('button', { name: 'Close ticket', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('button', { name: 'Back to board', exact: true }).click();
    console.log('PASS Team drag-to-start, close, archive, restore, Clear Done and retained details');
    await page.getByRole('button', { name: 'Other client title', exact: true }).click();
    await page.setViewportSize({ width: 1440, height: 1000 });
    if (!process.env.BROWSER_SKIP_SCREENSHOTS) await page.screenshot({ path: path.join(artifacts, 'desktop.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForTimeout(200);
    if (!process.env.BROWSER_SKIP_SCREENSHOTS) await page.screenshot({ path: path.join(artifacts, 'mobile.png') });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2);
    assert.equal(overflow, false, 'mobile document overflows');
    const ticketBounds = await page.locator('.ticket').boundingBox();
    assert.ok(ticketBounds.y >= 0 && ticketBounds.y < 100, 'mobile ticket opens within the viewport');
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('navigation', { name: 'Board columns' }).getByRole('button', { name: /^Review/ }).click();
    await page.getByRole('region', { name: 'Review', exact: true }).waitFor({ state: 'visible' });
    for (const tab of ['workspace', 'projects', 'repository']) {
        await page.goto(base + `/?tab=${tab}&project=${p.id}`);
        await page.locator('header.top').waitFor();
        if (tab === 'workspace') await page.getByRole('region', { name: 'Working now', exact: true }).waitFor();
        if (tab === 'repository') {
            const sections = page.getByRole('navigation', { name: 'Repository sections' });
            await sections.getByRole('button', { name: /^Pull requests/ }).click();
            await sections.getByRole('button', { name: /^Branches/ }).click();
        }
        for (const [size, width, height] of [['desktop', 1440, 1000], ['mobile', 390, 844]]) {
            await page.setViewportSize({ width, height });
            assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2), false, `${tab} ${size} overflows`);
            if (tab === 'workspace' && size === 'mobile') {
                const first = await page.locator('.workspace-layout.has-attention').count() ? page.locator('.overview-attention') : page.locator('#working-now');
                assert.ok((await first.boundingBox()).y < 250, 'attention or current work leads the first phone viewport');
            }
            if (!process.env.BROWSER_SKIP_SCREENSHOTS) await page.screenshot({ path: path.join(artifacts, `team-${tab}-${size}.png`) });
        }
    }
    assert.deepEqual(errors, []);
    console.log('PASS desktop/mobile layout, no JavaScript errors');
    await browser.close();
    console.log('Artifacts: ' + artifacts);
})().catch(e => { console.error(e.message); process.exit(1); });
