#!/bin/sh
# Regenerates third_party/rqlite/THIRD_PARTY_LICENSES.txt: the licences of every Go module that is statically linked into
# the rqlite release binary Werkbord Team bundles, taken from the module graph of cmd/rqlited at the pinned commit (a clone
# of the release's tag, which is refused unless it is the pinned commit, so that the project's own replace directives, such as
# the SQLite binding it forks, are the ones used).
#
#   scripts/gen-rqlite-notices.sh
#
# Needs git, the Go toolchain and network access to the Go module proxy. The result is committed; a release does not
# regenerate it. See docs/TEAM_STORAGE.md ("Bumping the pinned rqlite").
set -eu

cd "$(dirname "$0")/.."
ROOT=$(pwd)
MANIFEST=internal/team/infra/rqlite/manifest.go
version=$(sed -n 's/^const Version = "\(.*\)"$/\1/p' "$MANIFEST")
commit=$(sed -n 's/^const SourceCommit = "\(.*\)"$/\1/p' "$MANIFEST")
[ -n "$version" ] && [ -n "$commit" ] || { echo "gen-rqlite-notices: $MANIFEST is not what this script expects" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT INT TERM
git clone -q --depth 1 --branch "v$version" https://github.com/rqlite/rqlite.git "$work/src" || { echo "gen-rqlite-notices: cannot fetch rqlite v$version" >&2; exit 1; }
[ "$(git -C "$work/src" rev-parse HEAD)" = "$commit" ] || { echo "gen-rqlite-notices: tag v$version is not the pinned commit" >&2; exit 1; }
cd "$work/src"

out="$ROOT/third_party/rqlite/THIRD_PARTY_LICENSES.txt"
{
  cat <<EOT
Third-party software in the bundled rqlite binary (rqlite v$version)
==================================================================

Werkbord Team ships the unmodified release binary of rqlite (https://github.com/rqlite/rqlite,
MIT licence, see LICENSE in this directory). The rqlite binary is statically linked with the Go
modules below; their licences follow, as their terms require. This file is generated by
scripts/gen-rqlite-notices.sh from the module graph of github.com/rqlite/rqlite/v${version%%.*}/cmd/rqlited at the
pinned commit; do not edit it by hand.
EOT
  for os in darwin linux; do
    for arch in amd64 arm64; do
      CGO_ENABLED=1 GOOS=$os GOARCH=$arch go list -deps -f '{{if .Module}}{{.Module.Path}} {{.Module.Dir}}{{end}}' ./cmd/rqlited 2>/dev/null
    done
  done | sort -u | grep -v '^$' | while read -r mod dir; do
    [ "$mod" = "github.com/rqlite/rqlite/v${version%%.*}" ] && continue
    printf '\n----------------------------------------------------------------------\nModule: %s\n----------------------------------------------------------------------\n' "$mod"
    found=0
    for f in "$dir"/LICENSE* "$dir"/LICENCE* "$dir"/COPYING* "$dir"/NOTICE* "$dir"/PATENTS*; do
      [ -f "$f" ] || continue
      found=1
      printf '[%s]\n' "$(basename "$f")"
      cat "$f"
      printf '\n'
    done
    [ "$found" = 1 ] || echo "(the module ships no licence file; see its repository)"
  done
  printf '\n----------------------------------------------------------------------\nThe Go standard library and runtime (linked into every Go program)\n----------------------------------------------------------------------\n'
  cat "$ROOT/third_party/go/LICENSE"
} > "$out"
echo "gen-rqlite-notices: wrote $out ($(grep -c '^Module:' "$out") modules)"
