#!/bin/sh
# Regenerates third_party/nebula/THIRD_PARTY_LICENSES.txt: the licences of every Go module that is statically
# linked into the Nebula release binary Werkbord Team bundles, taken from the module graph of
# github.com/slackhq/nebula/cmd/nebula at the pinned version.
#
#   scripts/gen-nebula-notices.sh            uses the version pinned in internal/team/infra/nebula/manifest.go
#   scripts/gen-nebula-notices.sh 1.11.2     names one (when bumping the pin, run this with the new version first)
#
# Needs the Go toolchain and network access to the Go module proxy. The result is committed; a release
# does not regenerate it. See docs/TEAM_NETWORK.md ("Bumping the pinned Nebula").
set -eu

cd "$(dirname "$0")/.."
ROOT=$(pwd)
version=${1:-$(sed -n 's/^const Version = "\(.*\)"$/\1/p' internal/team/infra/nebula/manifest.go)}
[ -n "$version" ] || { echo "gen-nebula-notices: cannot tell which Nebula version to use" >&2; exit 1; }

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT INT TERM
cd "$work"
cat > go.mod <<EOF
module notices
go 1.26
EOF
GOFLAGS=-mod=mod go get "github.com/slackhq/nebula@v$version" >/dev/null 2>&1 || { echo "gen-nebula-notices: cannot fetch nebula v$version" >&2; exit 1; }

out="$ROOT/third_party/nebula/THIRD_PARTY_LICENSES.txt"
{
  cat <<EOF
Third-party software in the bundled Nebula binary (Nebula v$version)
==================================================================

Werkbord Team ships the unmodified release binary of Nebula (https://github.com/slackhq/nebula,
MIT licence, see LICENSE in this directory) and links Nebula's \`cert\` package. The Nebula binary is
statically linked with the Go modules below; their licences follow, as their terms require.
This file is generated by scripts/gen-nebula-notices.sh from the module graph of
github.com/slackhq/nebula/cmd/nebula at the pinned version; do not edit it by hand.
EOF
  for os in darwin linux windows; do
    for arch in amd64 arm64; do
      GOFLAGS=-mod=mod GOOS=$os GOARCH=$arch go list -deps -f '{{if .Module}}{{.Module.Path}} {{.Module.Dir}}{{end}}' github.com/slackhq/nebula/cmd/nebula
    done
  done | sort -u | grep -v '^$' | while read -r mod dir; do
    printf '\n----------------------------------------------------------------------\nModule: %s\n----------------------------------------------------------------------\n' "$mod"
    found=0
    for f in "$dir"/LICENSE* "$dir"/LICENCE* "$dir"/COPYING* "$dir"/NOTICE* "$dir"/PATENTS*; do
      [ -f "$f" ] || continue
      found=1
      printf '[%s]\n' "$(basename "$f")"
      cat "$f"
      printf '\n'
    done
    [ "$found" = 1 ] || echo "(the module ships no licence file; see its repository)"
  done
  printf '\n----------------------------------------------------------------------\nThe Go standard library and runtime (linked into every Go program)\n----------------------------------------------------------------------\n'
  cat "$ROOT/third_party/go/LICENSE"
} > "$out"
echo "gen-nebula-notices: wrote $out ($(grep -c '^Module:' "$out") modules)"
